[package]
name = "slang-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
tempfile = "3"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
flate2 = "1.0"
tar = "0.4"
